apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c100-application-metabase-admin
  namespace: c100-application-metabase
subjects:
  - kind: Group
    name: "github:family-justice"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: PrivilegedRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: Group
  name: system:serviceaccounts:c100-application-metabase
  apiGroup: rbac.authorization.k8s.io
