---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pathfinder.service.justice.gov.uk
  namespace: pathfinder-prod
spec:
  secretName: pathfinder-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'pathfinder.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'pathfinder.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
