apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: opa
spec:
  limits:
  - default:
      cpu: 80m
      memory: 400Mi
    defaultRequest:
      cpu: 4m
      memory: 50Mi
    type: Container
