kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-cla-frontend-staging-admin
  namespace: laa-cla-frontend-staging
subjects:
  - kind: Group
    name: "github:laa-get-access"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
