apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: check-financial-eligibility-production

  change in a single namespace

spec:
  limits:
  - default:
      cpu: 250m
      memory: 500Mi
    defaultRequest:
      cpu: 125m
      memory: 250Mi
    type: Container
