kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: serviceaccount-admin
  namespace: check-financial-eligibility-production
subjects:
- kind: ServiceAccount
  name: default
  namespace: check-financial-eligibility-production
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
