kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custody-dev-admin
  namespace: custody-dev
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
