kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gdavies-dev-admin
  namespace: gdavies-dev
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: gdavies-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: gdavies-dev
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: gdavies-dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
