apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: offender-management-preprod
spec:
  limits:
  - default:
      cpu: 300m
      memory: 750Mi
    defaultRequest:
      cpu: 10m
      memory: 250Mi
    type: Container
