kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whereabouts-api-dev-admin
  namespace: whereabouts-api-dev
subjects:
  - kind: Group
    name: "github:dps-core"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: whereabouts-api-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci 
  namespace: whereabouts-api-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: whereabouts-api-dev
subjects:
- kind: ServiceAccount
  name: tiller
- kind: ServiceAccount
  name: circleci
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
