kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toby-myapp-dev-admin
  namespace: toby-myapp-dev
subjects:
  - kind: Group
    name: "github:prison-visits-booking"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
