apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: apply-for-legal-aid-prod-cert
  namespace: laa-apply-for-legalaid-production
spec:
  secretName: apply-for-legal-aid-tls-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'apply-for-legal-aid.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'apply-for-legal-aid.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
