---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-apply-for-legalaid-production-admin
  namespace: laa-apply-for-legalaid-production
subjects:
  - kind: Group
    name: "github:laa-apply-for-legal-aid"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: laa-apply-for-legalaid-production
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: laa-apply-for-legalaid-production
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: laa-apply-for-legalaid-production
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
