apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: sentence-planning-preprod
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 250Mi
    type: Container
