apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: formbuilder-platform-dev
spec:
  limits:
  - default:
      cpu: 250m
      memory: 300Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
