apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: uat-claim-criminal-injuries-compensation-cert
  namespace: claim-criminal-injuries-compensation-uat
spec:
  secretName: uat-claim-criminal-injuries-compensation-cert-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: uat.claim-criminal-injuries-compensation.service.justice.gov.uk
  acme:
    config:
    - dns01:
        provider: route53-cloud-platform
      domains:
      - uat.claim-criminal-injuries-compensation.service.justice.gov.uk
