apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: data-capture-service-cert-uat
  namespace: claim-criminal-injuries-compensation-uat
spec:
  secretName: data-capture-service-cert-secret-uat
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  acme:
    config:
    - dns01:
        provider: route53-cloud-platform
      domains:
      - claim-criminal-injuries-compensation.service.justice.gov.uk
      - data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk
  commonName: claim-criminal-injuries-compensation.service.justice.gov.uk
  dnsNames:
  - claim-criminal-injuries-compensation.service.justice.gov.uk
  - data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk
