kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-services-staging-admins
  namespace: formbuilder-services-staging
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
  
# Bind admin role for namespace to team group & publisher ServiceAccount
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-services-staging-service-account
  namespace: formbuilder-services-staging
subjects:
  # dev, staging and production Publisher service accounts
  # are admins, so that they can both deploy to either
  - kind: ServiceAccount
    name: formbuilder-publisher-workers-dev
    namespace: formbuilder-platform-dev
  - kind: ServiceAccount
    name: formbuilder-publisher-workers-staging
    namespace: formbuilder-platform-staging
  - kind: ServiceAccount
    name: formbuilder-publisher-workers-production
    namespace: formbuilder-platform-production
  # ...but only the staging service token cache can read the staging
  # service tokens
  - kind: ServiceAccount
    name: formbuilder-service-token-cache-staging
    namespace: formbuilder-platform-staging
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
