kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: moving-people-safely-staging-admin
  namespace: moving-people-safely-staging
subjects:
  - kind: Group
    name: "github:moving-people-safely-devs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: moving-people-safely-staging # Your namespace `<servicename-env>`
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: moving-people-safely-staging # Your namespace `<servicename-env>`
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: moving-people-safely-staging # Your namespace `<servicename-env>`
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
