apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: formbuilder-services-dev
spec:
  limits:
  - default:
      cpu: 150m
      memory: 300Mi
    defaultRequest:
      cpu: 10m
      memory: 128Mi
    type: Container
