---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dev.pathfinder.service.justice.gov.uk
  namespace: pathfinder-dev
spec:
  secretName: pathfinder-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'dev.pathfinder.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'dev.pathfinder.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
