kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-api-access-staging-admin
  namespace: nomis-api-access-staging
subjects:
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: nomis-api-access-staging
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: nomis-api-access-staging
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: nomis-api-access-staging 
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
