kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-monitoring-admins
  namespace: formbuilder-monitoring
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: formbuilder-monitoring
    namespace: formbuilder-monitoring
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
