apiVersion: v1
kind: ServiceAccount
metadata:
  name: dsojenkins
  namespace: check-my-diary-prod

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dsojenkins
  namespace: check-my-diary-prod
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
      - "networkpolicies"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "service-monitor"
      - "servicemonitors"
      - "prometheusrules"
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "networkpolicies"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dsojenkins
  namespace: check-my-diary-prod
subjects:
- kind: ServiceAccount
  name: dsojenkins
  namespace: check-my-diary-prod
roleRef:
  kind: Role
  name: dsojenkins
  apiGroup: rbac.authorization.k8s.io
