kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prisoner-categorisation-tool-dev-admin
  namespace: prisoner-categorisation-tool-dev
subjects:
  - kind: Group
    name: "github:prisoner-categorisation-tool"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: prisoner-categorisation-tool-dev # Your namespace `<servicename-env>`
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: prisoner-categorisation-tool-dev # Your namespace `<servicename-env>`
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: prisoner-categorisation-tool-dev # Your namespace `<servicename-env>`
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
