kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-api-access-production-admin
  namespace: nomis-api-access-production
subjects:
  - kind: Group
    name: "github:dps-production-releases"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: nomis-api-access-production
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: nomis-api-access-production
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: nomis-api-access-production 
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
