kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cccd-api-sandbox-admin
  namespace: cccd-api-sandbox
subjects:
  - kind: Group
    name: "github:crime-billing-online"

another change

    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
