---
# Source: formbuilder-services/templates/certificate.yaml
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-wildcard
  namespace: formbuilder-services-live-staging
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.staging.form.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - '*.staging.form.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform

