apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-internal
  namespace: money-to-prisoners-test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-internal
  namespace: money-to-prisoners-test
rules:
  - apiGroups:
      - ""
    resources:
      - deployment
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-internal
  namespace: money-to-prisoners-test
subjects:
  - kind: ServiceAccount
    name: pod-internal
    namespace: money-to-prisoners-test
roleRef:
  kind: Role
  name: pod-internal
  apiGroup: rbac.authorization.k8s.io
