apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: money-to-prisoners-test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: circleci
  namespace: money-to-prisoners-test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: circleci
  namespace: money-to-prisoners-test
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: money-to-prisoners-test
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
