kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pecs-move-platform-backend-staging-admin
  namespace: pecs-move-platform-backend-staging
subjects:
  - kind: Group
    name: "github:pecs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
