kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth0-inactive-user-check-prod-admin
  namespace: auth0-inactive-user-check-prod
subjects:
  - kind: Group
    name: "github:secops"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
