kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: becca-test-app-dev-admin
  namespace: becca-test-app-dev
subjects:
  - kind: Group
    name: "github:tactical-products"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
