apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: digital-prison-services-dev

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: digital-prison-services-dev
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - "create"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: digital-prison-services-dev
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: digital-prison-services-dev
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
