kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prison-visits-booking-staging-admin
  namespace: prison-visits-booking-staging
subjects:
  - kind: Group
    name: "github:prison-visits-booking"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
