---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: preprod.pathfinder.service.justice.gov.uk
  namespace: pathfinder-preprod
spec:
  secretName: pathfinder-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'preprod.pathfinder.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'preprod.pathfinder.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
