apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: laa-cla-public-production
spec:
  limits:
  - default:
      cpu: 250m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
