kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emile-sample-app-dev-admin
  namespace: emile-sample-app-dev
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
