kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-financial-eligibility-staging-admin
  namespace: check-financial-eligibility-staging
subjects:
  - kind: Group
    name: "github:laa-apply-for-legal-aid"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: check-financial-eligibility-staging
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: check-financial-eligibility-staging
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: check-financial-eligibility-staging
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
