apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: 10000m
    requests.memory: 24Gi
    limits.cpu: 10000m
    limits.memory: 24Gi
