kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-get-access-service-improvement-admin
  namespace: laa-get-access-service-improvement
subjects:
  - kind: Group
    name: "github:laa-get-access-service-improvement"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:laa-get-access-data-and-reporting"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
