kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-book-secure-move-api-production-admin
  namespace: hmpps-book-secure-move-api-production
subjects:
  - kind: Group
    name: "github:pecs"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
