apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: court-probation-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: court-probation-dev-admin
  namespace: court-probation-dev
subjects:
  - kind: Group
    name: "github:ndelius"
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: circleci
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: court-probation-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: court-probation-dev
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: court-probation-dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
