kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cica-development-admin
  namespace: cica-development
subjects:
  - kind: Group
    name: "github:cica"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: cica-development
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: cica-development
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: cica-development
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
