on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - name: Format source code files
      uses: ministryofjustice/github-action-code-formatter@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
