on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      - name: Hello World action step
        id: hello
        uses: ministryofjustice/cloud-platform-github-actions-env-repo@v1.5
