on: [push]

jobs:
  run_tools:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-tools:1.4-test
    steps:
      - uses: actions/checkout@master
      - run: pwd
      - run: ls
      - run: ruby .github/workflows/action.rb
